name: "Lintje"
description: "A Git Linter for People. Validate your commits on every push."
author: "Tom de Bruijn <tom@tomdebruijn.com>"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  branch_validation:
    description: "Branch name validation to write better branch names"
    required: false
    default: "true"
  hints:
    description: "Lintje hints to write better commits"
    required: false
    default: "true"
branding:
  icon: "check-square"
  color: "purple"
